wandb_version: 1

epochs:
  desc: null
  value: 1000
model:
  desc: null
  value: MLP
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
time_size:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adamW
loss:
  desc: null
  value: Huber
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717622402.196161
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.8.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
