wandb_version: 1

epochs:
  desc: null
  value: 500
model:
  desc: null
  value: MLP_HNN
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 32
time_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adamW
loss:
  desc: null
  value: MSE
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717581568.065444
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
