model: PULL
sob: 
  - True
  - True
sob_a: 
  - 1.00
  - 0.15
a : 0.01
opti : adamW
reg : none
loss: Huber
acts : 
  - relu
  - 
epochs: 100
modelsize : 256
batchsize : 128
timesize : 32
lr: 0.0001
split: 0.9
device: cpu
single: False
noloops: True 
samples: 15
bias: True
