wandb_version: 1

epochs:
  desc: null
  value: 150
model:
  desc: null
  value: REC
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 8
time_size:
  desc: null
  value: 128
optimizer:
  desc: null
  value: adamW
loss:
  desc: null
  value: Huber
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717524461.021149
    t:
      1:
      - 1
      - 55
      - 76
      2:
      - 1
      - 55
      - 76
      3:
      - 1
      - 16
      - 23
      4: 3.8.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
