wandb_version: 1

epochs:
  desc: null
  value: 100
model:
  desc: null
  value: MLP
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
time_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adamW
loss:
  desc: null
  value: Huber
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720042341
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
